name: py to exe


on:
  push:
  pull_request:

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  TOKEN: ${{ secrets.TOKEN }}

defaults:
  run:
    shell: cmd

jobs:
  build:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v4.1.7
      with:
        sparse-checkout: .
    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: py to exe
      run: |
          chcp 65001
          pyinstaller --noconfirm --onefile --console --add-data "License.txt;." --icon "Vrelicon.ico"  "dol-beautification-module-automatic-generator.py"

    - run: |
        copy /v /y dist\dol-beautification-module-automatic-generator.exe .

    - name: push
      run: |
        git -v
        git branch --show-current
        git config user.email "pl816098@gmail.com"
        git config user.name "Paul-16098"
        git push origin HEAD:main
        git checkout origin/main
        git status
        git merge main
        git add .
        git commit -m "GitHub Actions Merge changes"
        git push origin HEAD:main
        git pull origin main -v

    - name: releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-Release"
        prerelease: false
        title: "最新的自動編譯版本"
        files: |
            dol-beautification-module-automatic-generator.exe
