name: py to exe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    shell: cmd
    working-directory: .

jobs:
  build:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: init
      run: |
        chcp 65001
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: py to exe
      run: |
        pyinstaller --noconfirm --onedir --console --icon "Vrelicon.ico" --onefile ".\dol美化模组自动生成器.exe"
        del build /f /s /q
        rmdir build /s /q
        del dol美化模组自动生成器.spec /f /s /q
        copy /v /y dist\dol美化模组自动生成器.exe .
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: last-Release  # 指定發行版的標籤名稱
        release_name: last-Release  # 指定發行版的名稱
        body: |
          last-Release
        draft: false
        prerelease: false