name: py to exe


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  TOKEN: ${{ secrets.TOKEN }}

defaults:
  run:
    shell: cmd

jobs:
  build:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v4.1.2
      with:
        sparse-checkout: .
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: py to exe
      run: |
          chcp 65001
          pyinstaller --noconfirm --onefile --console --icon "Vrelicon.ico"  "dol-beautification-module-automatic-generator.py"

    - name: del temp
      run: |
        del build /f /s /q
        rmdir build /s /q
        del dol-beautification-module-automatic-generator.spec /f /s /q
        copy /v /y dist\dol-beautification-module-automatic-generator.exe .

    - name: push
      run: |
        git config --global user.email "pl816098@gmail.com"
        git config --global user.name "Paul-16098"
        git push origin HEAD:main
        git checkout origin/main
        git merge main
        git commit
        git push origin HEAD:main

    - name: releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-Release"
        prerelease: false
        title: "最新的自動編譯版本"
        files: |
            dol-beautification-module-automatic-generator.exe
