name: py to exe


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  TOKEN: ${{ secrets.TOKEN }}

defaults:
  run:
    shell: cmd

jobs:
  build:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v4.1.2
      with:
        sparse-checkout: .
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: "3.12"
    - name: init
      run: |
        chcp 65001
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: py to exe
      run: pyinstaller --noconfirm --console --icon "Vrelicon.ico" --onefile "dol美化模组自动生成器.py"

    - name: del temp
      run: |
        del build /f /s /q
        rmdir build /s /q
        del dol美化模组自动生成器.spec /f /s /q
        copy /v /y dist\dol美化模组自动生成器.exe .

  Release:
    needs: build  # 添加 needs 關鍵字，指定依賴於 build 作業
    runs-on: [windows-latest]
    
    steps:
        - uses: actions/checkout@v4.1.2

        - name: init
          run: |

        - name: Create Release
          id: create_release
          uses: actions/create-release@v1.1.4
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
          with:
            tag_name: pull-${{ github.ref_name }}  # 指定發行版的標籤名稱
            release_name: Release-${{ github.job_workflow_sha }}  # 指定發行版的名稱
            body: |
              自動編譯版本
            draft: false
            prerelease: false

        - name: Upload Release Asset
          uses: actions/upload-release-asset@v1.0.2
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: dol美化模组自动生成器.exe
            asset_name: dol美化模组自动生成器.exe
            asset_content_type: application/octet-stream
